"""initial_migration

Revision ID: 2484c0f7e695
Revises:
Create Date: 2025-10-28 15:32:03.088641

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2484c0f7e695"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jugadores",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("nombre", sa.String(), nullable=False),
        sa.Column("correo", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("correo"),
        sa.UniqueConstraint("nombre"),
    )
    op.create_index(op.f("ix_jugadores_id"), "jugadores", ["id"], unique=False)
    op.create_table(
        "partidas",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("id_jugador_x", sa.String(), nullable=True),
        sa.Column("id_jugador_o", sa.String(), nullable=True),
        sa.Column("fecha_inicio", sa.DateTime(), nullable=False),
        sa.Column("fecha_fin", sa.DateTime(), nullable=True),
        sa.Column("id_ganador", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["id_ganador"],
            ["jugadores.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_jugador_o"],
            ["jugadores.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_jugador_x"],
            ["jugadores.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "jugadas",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("id_partida", sa.String(), nullable=True),
        sa.Column("id_jugador", sa.String(), nullable=True),
        sa.Column("turno", sa.Integer(), nullable=False),
        sa.Column("fila", sa.Integer(), nullable=False),
        sa.Column("columna", sa.Integer(), nullable=False),
        sa.Column("fecha_jugada", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_jugador"],
            ["jugadores.id"],
        ),
        sa.ForeignKeyConstraint(
            ["id_partida"],
            ["partidas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jugadas_turno"), "jugadas", ["turno"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jugadas_turno"), table_name="jugadas")
    op.drop_table("jugadas")
    op.drop_table("partidas")
    op.drop_index(op.f("ix_jugadores_id"), table_name="jugadores")
    op.drop_table("jugadores")
    # ### end Alembic commands ###
